### PR TITLE
Fix finish backwards shift overwriting next entry

### LINKED ISSUE #62: Missing key after commit and flush
After deleting a couple of keys and committing and flushing, an existing key-value pair was not found. 

I have a test here that exposes the bug: https://github.com/paritytech/paritydb/compare/failing-flush. The last assertion fails.

### PR DESCRIPTION
**Pull request by andresilva**
Fixes #62.

### CODE REVIEW

File: paritydb/src/flush/writer.rs [hunk 1]
```diff
@@ -217,7 +217,23 @@ impl<'op, 'db, I: Iterator<Item = Operation<'op>>> OperationWriter<'db, I> {
...
+					Space::Occupied(space) => {
+						let min_offset = min_offset_for_space(space.data, self.prefix_bits, self.field_body_size) as isize;
+						let diff = space.offset as isize - (-self.shift) - min_offset;
+
+						if diff < 0 {
+							write_empty_bytes(self.buffer.as_raw_mut(), (-diff) as usize);
+						}
+					},
+					_ => {
+						write_empty_bytes(self.buffer.as_raw_mut(), (-self.shift) as usize);
```
Comment (andresilva) [inline paritydb/src/flush/writer.rs]: Is this correct or should we iterate over all the next `Space::Empty` and `write_empty_bytes` with `space.size`?

File: paritydb/src/flush/writer.rs [hunk 2]
```diff
@@ -217,7 +217,23 @@ impl<'op, 'db, I: Iterator<Item = Operation<'op>>> OperationWriter<'db, I> {
 				// do not advance iterator
 				// finish shift backwards
 				assert!(self.shift < 0, "we are in delete mode");
-				write_empty_bytes(self.buffer.as_raw_mut(), (-self.shift) as usize);
+
+				match space {
+					// if the next space is occupied we'll only add empty bytes until its minimum offset (iff the shift
```
Comment (debris) [inline paritydb/src/flush/writer.rs]: `iff` -> `if`

File: paritydb/src/flush/writer.rs [hunk 3]
```diff
@@ -158,7 +158,7 @@ impl<'op, 'db, I: Iterator<Item = Operation<'op>>> OperationWriter<'db, I> {
 		}
 
 		let space = self.spaces.peek().expect("TODO: db end?")?;
-		let d = decision(operation, space, self.shift, self.field_body_size, self.prefix_bits);
+		let d = decision(operation, space.clone(), self.shift, self.field_body_size, self.prefix_bits);
```
Comment (debris) [inline paritydb/src/flush/writer.rs]: the whole idea of `decision` function was to omit using space in this function. Imo, it would be more clear, to introduce new `Decision` enum type.

File: paritydb/src/flush/writer.rs (hunk 2 above)
Comment (tomusdrw) [reply paritydb/src/flush/writer.rs]: iff = if and only if

File: paritydb/src/flush/writer.rs (hunk 3 above)
Comment (debris) [reply paritydb/src/flush/writer.rs]: actually `FinishBackwardShift`could be renamed to `BackwardShift` as we should never assume that it will finish the shift

File: paritydb/src/flush/writer.rs (hunk 2 above)
Comment (debris) [reply paritydb/src/flush/writer.rs]: didn't know that ;)

**Comment by andresilva** [comment]
I changed the name to `BackwardShift` but I was thinking about it now and I don't think this conveys the correct meaning (at least to my understanding). In essence when we apply a `BackwardShift` what we're actually doing is just padding to compensate for whatever we might have removed, we're only actually shifting things backwards if we decide to pad less than we could. Does this make any sense?

**Comment by debris** [comment]
yes, the naming is unfortunate and doesn't describe the operation properly :/ maybe `InsertPadding` instead? I don't have a strong opinion about it

File: paritydb/src/flush/decision.rs [hunk 4]
```diff
@@ -133,7 +147,7 @@ pub fn decision<'o, 'db>(operation: Operation<'o>, space: Space<'db>, shift: isi
 				space_len: space.len,
 			}
 		} else {
-			Decision::FinishBackwardShift
+			Decision::BackwardShift { len: space.len }
```
Comment (debris) [inline paritydb/src/flush/decision.rs]: I think that this case should be treated differently than the others. When `space` is occupied, we pad `buffer` to the first possible position of either `operation` or `space`. Here, we need to always pad it to the first possible position of the `operation`, so the logic should:

- `decision` returns information that 1 space should be padded
- `step` does padding, reduces the shift
- `decision` is run with the same arguments, if shift is still non-zero, it returns the same information that 1 space should be padded
- ... and so on

File: paritydb/src/flush/decision.rs [hunk 5]
```diff
@@ -146,7 +160,9 @@ pub fn decision<'o, 'db>(operation: Operation<'o>, space: Space<'db>, shift: isi
 						data: space.data,
 					}
 				} else {
-					Decision::FinishBackwardShift
+					let min_offset = min_offset_for_space(space.data, prefix_bits, field_body_size);
+					let len = backward_shift_len(space.offset, min_offset, shift);
+					Decision::BackwardShift { len }
```
Comment (debris) [inline paritydb/src/flush/decision.rs]: this case is different than previous one. `space` is occupied, so we pad `buffer` to the first possible position of either `space` or `operation`. Here the `space`'s key is `Less` than `operation'`s key, so we need to pad to it. The code looks good. `backward_shift_len` should never return 0. Can you just add an assertion for that?

File: paritydb/src/flush/decision.rs [hunk 6]
```diff
@@ -164,7 +180,9 @@ pub fn decision<'o, 'db>(operation: Operation<'o>, space: Space<'db>, shift: isi
 						offset: space.offset,
 					}
 				} else {
-					Decision::FinishBackwardShift
+					let min_offset = min_offset_for_key(key, prefix_bits, field_body_size);
+					let len = backward_shift_len(space.offset, min_offset, shift);
+					Decision::BackwardShift { len }
```
Comment (debris) [inline paritydb/src/flush/decision.rs]: this is also fine. And again, it would be nice to have an assertion that `backward_shift_len` is not 0 ;)

File: paritydb/src/flush/decision.rs [hunk 7]
```diff
@@ -193,7 +211,9 @@ pub fn decision<'o, 'db>(operation: Operation<'o>, space: Space<'db>, shift: isi
 						data: space.data,
 					}
 				} else {
-					Decision::FinishBackwardShift
+					let min_offset = min_offset_for_space(space.data, prefix_bits, field_body_size);
+					let len = backward_shift_len(space.offset, min_offset, shift);
+					Decision::BackwardShift { len }
```
Comment (debris) [inline paritydb/src/flush/decision.rs]: this is fine ;)

File: paritydb/src/flush/decision.rs [hunk 8]
```diff
@@ -99,6 +101,18 @@ pub fn min_offset_for_key(key: &[u8], prefix_bits: u8, field_body_size: usize) -
...
 
+#[inline]
+fn backward_shift_len(offset: usize, min_offset: usize, shift: isize) -> usize {
+	let diff = offset as isize - (-shift) - min_offset as isize;
+
+	// we shift backwards at most `shift` and only the necessary to reach `min_offset`
+	if diff < 0 {
+		-diff as usize
+	} else {
+		0
```
Comment (debris) [inline paritydb/src/flush/decision.rs]: it is always called after `min_offset_for_space` which is called after `is_min_offset_for_space`, so this arm is unreachable. maybe places where this function is called so the calculations are not duplicated

e.g.

```rust
let min_offset = min_offset_for_space(...);
if is_min_offset(... ) {
  // do something
} else {
  let backward_shift_len = ...
  // do something else
}
```

File: paritydb/src/flush/decision.rs (hunk 4 above)
Comment (debris) [reply paritydb/src/flush/decision.rs]: tl;dr; everything is fine here ;)

File: paritydb/src/flush/writer.rs [hunk 9]
```diff
@@ -213,11 +213,12 @@ impl<'op, 'db, I: Iterator<Item = Operation<'op>>> OperationWriter<'db, I> {
...
 			},
-			Decision::FinishBackwardShift => {
+			Decision::BackwardShift { len } => {
 				// do not advance iterator
 				// finish shift backwards
 				assert!(self.shift < 0, "we are in delete mode");
-				write_empty_bytes(self.buffer.as_raw_mut(), (-self.shift) as usize);
+
+				write_empty_bytes(self.buffer.as_raw_mut(), len);
 				self.shift = 0;
```
[the remark this answers is not in the document]
Comment (debris) [reply paritydb/src/flush/writer.rs]: and maybe add an assertion after that shift should never be greater than `0`

[the remark this answers is not in the document]
Comment (debris) [reply paritydb/src/flush/writer.rs]: imo, that's the only change which is needed. Everything else is great :)

[the remark this answers is not in the document]
Comment (andresilva) [reply paritydb/src/flush/writer.rs]: I was thinking that after we put a value in it's place we wouldn't be able to shift anything afterwards but that's not the case, you're right we should only reduce it by `len`.

**Comment by andresilva** [comment]
Thanks for the review, I'm sure these comments will be useful in the future 😛 Updated according to your suggestions.

File: paritydb/src/flush/writer.rs (hunk 3 above)
Comment (debris) [reply paritydb/src/flush/writer.rs]: I believe that this `clone()` is redundant now ;)

**Comment by debris** [comment]
I love it! there is just one redundant `clone()` left :)

**Comment by debris** [comment]
that was fast 👍

**Comment by debris** [comment]
let's merge when the CI is green

**Comment by andresilva** [comment]
Indeed, it's like I was expecting your comment hehe 😝
